import numpy as np
import sys

eVars = []
rVars = []
var_num = None
cls_num = None

with open(sys.argv[1], 'r') as f1:
    with open(sys.argv[2], 'w') as f2:
        f2.write('c generated by max2dimacs.py\n')
        for idx, line in enumerate(f1):
            if line[0] != 'c':
                f2.write(line)
