import numpy as np
import sys

eVars = []
rVars = []
var_num = None
cls_num = None

with open(sys.argv[1], 'r') as f1:
    with open(sys.argv[2], 'w') as f2:
        f2.write('c generated by max2ere.py\n')
        for idx, line in enumerate(f1):
            if line[0] != 'c' and line[0] != 'p':
                f2.write(line)
                continue

            if line[-1] == '\n':
                line = line[:-1]
            if line[:5] == 'c max':
                for n in line[5:].split(' ')[:-1]:
                    if n.strip() != '':
                        eVars.append(n.strip())
            elif line[:5] == 'c ind':
                for n in line[5:].split(' ')[:-1]:
                    if n.strip() != '':
                        rVars.append(n.strip())
            elif line[:5] == 'p cnf':
                var_num = line.split(' ')[2]
                cls_num = line.split(' ')[3]
                f2.write('p cnf %s %s\n' % (var_num, cls_num))
                f2.write('e ' + ' '.join(eVars) + ' 0\n')
                f2.write('r 0.5 ' + ' '.join(rVars) + ' 0\n')
                eVars2 = 'e'
                for i in range(1, int(var_num)+1):
                    if (str(i) not in eVars) and (str(i) not in rVars):
                        eVars2 += ' %s' % str(i)
                if len(eVars2) != 1:
                    f2.write(eVars2 + ' 0\n')
